package com.example.tp4;

import java.util.ArrayList;

public class DataDummy {

    public static ArrayList<Books> books = bookList();

    private static ArrayList<Books> bookList() {
        ArrayList<Books> books = new ArrayList<>();

        books.add(new Books("Buku Anak Harry Potter Dan Batu Bertuah", "J.K. Rowling", "Fantasy", 2014, "Seumur hidup, Harry Potter tidak pernah berurusan dengan sihir. Dia tinggal bersama keluarga Dursley yang kejam dan Dudley, putra mereka yang menyebalkan. Kamar Harry cuma lemari sempit di kolong tangga, dan selama sebelas tahun, ulang tahunnya tak pernah dirayakan. Namun, tiba-tiba datang burung hantu membawa surat misterius: surat berisi undangan ke tempat menakjubkan bernama Sekolah Sihir Hogwarts. Dan di sana bukan hanya ada banyak teman, pertandingan olahraga naik sapu terbang, dan sihir dalam segala hal dari pelajaran sampai makanan tapi juga ada takdir luar biasa yang sudah lama menantinya. Jika Harry mampu bertahan hidup.","android.resource://com.example.tp4/drawable/books1", 0));
        books.add(new Books("Harry Potter and the Deathly Hallows", "J.K. Rowling", "Fantasy", 2018, "Ketika naik ke motor Hagrid dan melesat ke langit untuk meninggalkan Privet Drive terakhir kali, Harry Potter tahu bahwa Lord Voldemort dan para Pelahap Maut tak jauh di belakangnya. Mantra pelindung yang selama ini menjaga Harry kini sudah meredup, tetapi dia tidak bisa terus bersembunyi. \n" +
                " Sang Pangeran Kegelapan menghantui semua orang yang disayangi oleh Harry. Guna menghentikannya, Harry harus menemukan dan menghancurkan semua Horcrux yang tersisa. Pertempuran terakhir akan segera dimulai. Harry akan maju dan menghadapi musuhnya.","android.resource://com.example.tp4/drawable/cover1", 0));
        books.add(new Books("Harry Potter and The Prisoner of Azkaban", "J.K. Rowling", "Fantasy", 2017, "Ketika Bus Ksatria membelah kegelapan malam dan berhenti mendadak di hadapan Harry Potter, maka dimulailah tahun ajaran berikutnya di Hogwarts yang jauh dari biasa-biasa saja.\n" +
                " \n" +
                " Sirius Black, pembunuh massal dan pengikut Lord Voldemort, kabur dari penjara Azkaban— dan konon dia memburu Harry.\n" +
                " \n" +
                " Pada pelajaran Ramalan pertama, Profesor Trelawney melihat terawangan kematian dalam ampas teh anak itu...\n" +
                " \n" +
                " Namun, tak ada yang lebih menakutkan daripada para Dementor, sosok-sosok pengisap jiwa, yang gentayangan di sekeliling sekolah.\n","android.resource://com.example.tp4/drawable/cover2", 0));
        books.add(new Books("The Hunger Games", "Suzanne Collins", "Adventure", 2025, "Dua puluh empat peserta. Hanya satu pemenang yang selamat. Amerika Utara musnah sudah. Kini di bekasnya berdiri negara Panem, dengan Capitol sebagai pusat kota yang dikelilingi dua belas distrik. Katniss, gadis 16 tahun, tinggal bersama adik perempuan dan ibunya di distrik termiskin di Distrik12. Karena pemberontakan di masa lalu terhadap Capitol, setiap tahun masing-masing Distrik harus mengirim seorang anak perempuan dan anak lelaki untuk bertarung sampai mati dan ditayangkan secara langsung di acara televisi The Hunger Games. Hanya ada satu pemenang setiap tahun. Tujuannya adalah membunuh atau dibunuh. Ketika adik perempuannya terpilih mengikuti The Hunger Games, Katniss mengajukan diri untuk menggantikannya. Dan dimulailah pertarungan yang takkan pernah dilupakan Capitol.","android.resource://com.example.tp4/drawable/cover3", 0));
        books.add(new Books("The Hunger Games #2 Catching Fire", "Suzanne Collins", "Adventure", 2025, "Api Pemberontakan sudah tersulut. Dan Capitol ingin membalas dendam. Katniss Everdeen berhasil keluar sebagai pemenang Hunger Games bersama Peeta Mellark. Tapi kemenangan itu menyulut kemarahan Capitol. Kemenangan Katniss ternyata membangkitkan semangat pemberontakan di beberapa distrik untuk menentang kekuasaan Presiden Snow yang kejam. Presiden Snow mengancam Katniss untuk meredakan kegelisahan penduduk distrik dalam Tur Kemenangan-nya. Satu-satunya cara untuk meredakan kegelisahan penduduk adalah membuktikan bahwa dia dan Peeta saling mencintai tanpa ada keraguan sedikit pun. Jika gagal, keluarga dan semua orang yang disayangi Katniss menjadi taruhannya....","android.resource://com.example.tp4/drawable/cover4", 0));
        books.add(new Books("The Hunger Games #3 Mockingjay", "Suzanne Collins", "Adventure", 2025, "Katniss Everdeen selamat dari Hunger Games dua kali. Tapi Katniss belum sepenuhnya aman dari ancaman Capitol meskipun sekarang ia dalam lindungan Distrik 13. Pemberontakan makin merajalela di distrik-distrik untuk menjatuhkan Capitol. Kini tak ada seorang pun yang dicintai Katniss aman karena Presiden Snow ingin menumpas revolusi dengan menghancurkan Mockingjay... bagaimanapun caranya.","android.resource://com.example.tp4/drawable/cover5", 0));
        books.add(new Books("Harry Potter and The Goblet of Fire", "J.K. Rowling", "Fantasy", 2017, "Di Hogwarts, Profesor Dumbledore mengumumkan bahwa Alastor \"Mad-Eye\" Moody menjadi guru Pertahanan Terhadap Ilmu Hitam yang baru. Hogwarts akan menjadi tuan rumah Turnamen Triwizard. Hanya para penyihir berusia tujuh belas tahun ke atas yang boleh ikut—namun Harry tetap berkhayal menjadi juara dalam kompetisi itu.\n" +
                " \n" +
                " Lalu pada Halloween, ketika Piala Api melakukan seleksi, Harry kaget saat dirinya terpilih. Dia harus melaksanakan tugas-tugas yang menantang maut, menghadapi naga-naga dan para penyihir Hitam. Tetapi, dengan bantuan para sahabat baiknya, Ron dan Hermione, dia mungkin akan berhasil—dan bertahan hidup.\n","android.resource://com.example.tp4/drawable/cover6", 0));
        books.add(new Books("Harry Potter and the Chamber of Secrets", "J.K. Rowling", "Fantasy", 2017, "\"Banyak yang dialami Harry Potter pada libur musim panasnya kali ini, di antaranya: ulang tahun paling payah, aneka peringatan menyeramkan dari peri-rumah bernama Dobby, dan kabur naik mobil terbang dari rumah keluarga Dursley bersama sahabatnya, Ron Weasley!\n" +
                " \n" +
                " Sekembalinya di Sekolah Sihir Hogwarts, Harry mendengar berbagai bisikan aneh menggema di koridor-koridor kosong—lalu serangan-serangan pun mulai. Para murid ditemukan dalam keadaan membatu...\n" +
                " \n" +
                " Peringatan mengerikan Dobby seolah jadi kenyataan.\"\n","android.resource://com.example.tp4/drawable/cover7", 0));
        books.add(new Books("Harry Potter and the Order of the Phoenix", "J.K. Rowling", "Fantasy", 2017, "Tidak banyak penyihir yang percaya (atau mau percaya) bahwa Voldermort telah kembali, termasuk Kementerian Sihir. Harry dan Dumbledore dianggap menyebar kabar bohong dan dianggap terganggu jiwanya. Meskipun demikian, masih banyak orang yang percaya pada Dumbledore, dan merek inilah yang tergabung dalam Orde Phoenix. Namun, karena situasi belum memungkinkan, mereka bergerak secara diam-diam untuk menghindari kecurigaan dari Kementerian. Mereka menggunakan kediaman Sirius, Grimmauld Place nomor 12 sebagai Markas Besar sehingga Sirius tidak lagi dalam pelarian, tapi tetap bersembunyi karena pihak kementrian masih mencarinya.\n" +
                " \n" +
                " Sementara itu, Harry yang diawasi siang-malam (tanpa sepengetahuannya) oleh anggota Orde, semakin sering mengalami sakit pada bekas lukanya. Sekembalinya ke Hogwarts, Harry menghadapi persidangan karena mengeluarkan sihir di dunia Muggle dan emosinya sering tak terkendali. Pada suatu malam ia dikejutkan dengan hadirnya dementor di Privet Drive yang hendak menyerang dirinya dan Dudley. Untunglah ia berhasil menghasilkan patronus untuk melawan mereka. Namun, akibat dari hal ini, dia nyaris diusir oleh pamannya karena dikira menyerang Dudley menghadapi persidangan di Kementerian Sihir dan terancam dikeluarkan dari Hogwarts.\n" +
                " \n" +
                " Harry tidak sendirian: di Grimmauld Place berkumpul orde rahasia untuk melawan kekuatan gelap. Harry harus mengizinkan Profesor Snape mengajarinya cara melindungi diri dari rentetan serangan brutal Voldemort dari benaknya. Namun, serangan-serangan itu makin ganas dan Harry kehabisan waktu. Apakah Harry berhasil melakukan perlindungan diri? Apa yang akan terjadi dengan anggota Orde?","android.resource://com.example.tp4/drawable/cover8", 0));
        books.add(new Books("CAPTAIN AMERICA", "Collin KellyJackson LanzingTochi Onyebuchi", "fiction", 2022, "books.add(new Books(\"CAPTAIN AMERICA\", \"Collin KellyJackson LanzingTochi Onyebuchi\", \"fiction\", 2022, \"blurb\",\"android.resource://com.example.tp4/drawable/cover4\", 0));","android.resource://com.example.tp4/drawable/cover9", 0));
        books.add(new Books("AMAZING SPIDER-MAN/ULTIMATE UNIVERSE", "Deniz CampJoe KellyCody Ziglar", "fiction", 2025, "Joe Kelly and John Romita Jr. remind us who Peter Parker and SPIDER-MAN are! Plus, an exclusive prologue to this summer's blockbuster ULTIMATE event from Deniz Camp, Cody Ziglar & Jonas Scharf!","android.resource://com.example.tp4/drawable/cover14", 0));
        books.add(new Books("IRON MAN & HIS AWESOME FRIENDS/SPIDEY & HIS AMAZING FRIENDS", "Alberto Alburquerque", "fiction", 2025, "SWING INTO THIS YEAR'S FREE COMIC BOOK DAY SPECIAL WITH NEW AND FAVORITE CHARACTERS FROM TWO DISNEY JR. SHOWS! FIRST, ARMOR UP with Iron Man and his Awesome Friends, Iron Heart and Iron Hulk, in this not-to-be-missed all-new comic featuring characters from the forthcoming Disney Jr. show! Then the web-slinging fun continues with everyone's favorite heroes from Marvel's Spidey and His Amazing Friends! There's no shortage of baddies creating mischief in New York and Spidey, Ghost-Spider, and Spin need help keeping the city safe through thrilling activity pages and easy-to-read stories.","android.resource://com.example.tp4/drawable/cover13", 0));
        books.add(new Books("STAR WARS", "Marc GuggenheimAlex SeguraCharles Soule", "fiction", 2025, "CELEBRATING THE NEW ERA OF STAR WARS COMICS! LUKE SKYWALKER finds himself in a wretched hive of scum and villainy facing off against pirates! JEDI KNIGHTS QUI-GON JINN & TENSU RUN are on the hunt for the villainous CORLIS RATH! Who is the mysterious VANEE and what is his connection to DARTH VADER & KYLO REN?","android.resource://com.example.tp4/drawable/cover12", 0));
        books.add(new Books("MOON KNIGHT: FIST OF KHONSHU", "Joe KellyJed Mackay", "fiction", 2025, "Following Marc Spector’s triumphant return in BLOOD HUNT #4, Jed MacKay and Alessandro Cappuccio’s acclaimed run on Moon Knight continues in a special prelude issue to the new MOON KNIGHT: FIST OF KHONSHU ongoing series arriving this October. This previously unannounced issue follows up on Marc’s return, and not only is it an essential chapter, it’s also a perfect starting point for readers who want to jump into one of the hottest modern Marvel sagas. This issue underscores the scope of MacKay and Cappuccio’s riveting take on the Moon Knight mythos by spotlighting the now-iconic crew of the Midnight Mission, shedding light on recent developments, and setting the stage for Marc Spector’s next era!","android.resource://com.example.tp4/drawable/cover10", 0));
        books.add(new Books("FANTASTIC FOUR", "Ryan North", "fiction", 2025, "FANTASTIC TWO! As Ben recovers from what Doom has done to him, the Fantastic Four learn they're losing their powers at the one time they need them the most desperately! If they can't reverse the effect, they may be lost forever - and Doom will be unstoppable. But the family has an idea of how to get them back - and to do it safely. They need only recreate the circumstances that first gave them their powers. But when safety doesn't get them results, there is a more desperate path available to the Four - and they take it. It all comes down to this! A young woman. Her kid brother. The man she loves. His only friend... ...and a desperate launch into space.","android.resource://com.example.tp4/drawable/cover11", 0));


        return books;
    }
}
